from enum import Enum

from sai_thrift import sai_headers


class SaiStatus(Enum):
    SAI_STATUS_SUCCESS = sai_headers.SAI_STATUS_SUCCESS
    SAI_STATUS_FAILURE = sai_headers.SAI_STATUS_FAILURE
    SAI_STATUS_NOT_SUPPORTED = sai_headers.SAI_STATUS_NOT_SUPPORTED
    SAI_STATUS_NO_MEMORY = sai_headers.SAI_STATUS_NO_MEMORY
    SAI_STATUS_INSUFFICIENT_RESOURCES = sai_headers.SAI_STATUS_INSUFFICIENT_RESOURCES
    SAI_STATUS_INVALID_PARAMETER = sai_headers.SAI_STATUS_INVALID_PARAMETER
    SAI_STATUS_ITEM_ALREADY_EXISTS = sai_headers.SAI_STATUS_ITEM_ALREADY_EXISTS
    SAI_STATUS_ITEM_NOT_FOUND = sai_headers.SAI_STATUS_ITEM_NOT_FOUND
    SAI_STATUS_BUFFER_OVERFLOW = sai_headers.SAI_STATUS_BUFFER_OVERFLOW
    SAI_STATUS_INVALID_PORT_NUMBER = sai_headers.SAI_STATUS_INVALID_PORT_NUMBER
    SAI_STATUS_INVALID_PORT_MEMBER = sai_headers.SAI_STATUS_INVALID_PORT_MEMBER
    SAI_STATUS_INVALID_VLAN_ID = sai_headers.SAI_STATUS_INVALID_VLAN_ID
    SAI_STATUS_UNINITIALIZED = sai_headers.SAI_STATUS_UNINITIALIZED
    SAI_STATUS_TABLE_FULL = sai_headers.SAI_STATUS_TABLE_FULL
    SAI_STATUS_MANDATORY_ATTRIBUTE_MISSING = sai_headers.SAI_STATUS_MANDATORY_ATTRIBUTE_MISSING
    SAI_STATUS_NOT_IMPLEMENTED = sai_headers.SAI_STATUS_NOT_IMPLEMENTED
    SAI_STATUS_ADDR_NOT_FOUND = sai_headers.SAI_STATUS_ADDR_NOT_FOUND
    SAI_STATUS_OBJECT_IN_USE = sai_headers.SAI_STATUS_OBJECT_IN_USE
    SAI_STATUS_INVALID_OBJECT_TYPE = sai_headers.SAI_STATUS_INVALID_OBJECT_TYPE
    SAI_STATUS_INVALID_OBJECT_ID = sai_headers.SAI_STATUS_INVALID_OBJECT_ID
    SAI_STATUS_INVALID_NV_STORAGE = sai_headers.SAI_STATUS_INVALID_NV_STORAGE
    SAI_STATUS_NV_STORAGE_FULL = sai_headers.SAI_STATUS_NV_STORAGE_FULL
    SAI_STATUS_SW_UPGRADE_VERSION_MISMATCH = sai_headers.SAI_STATUS_SW_UPGRADE_VERSION_MISMATCH
    SAI_STATUS_NOT_EXECUTED = sai_headers.SAI_STATUS_NOT_EXECUTED
    SAI_STATUS_INVALID_ATTRIBUTE_0 = sai_headers.SAI_STATUS_INVALID_ATTRIBUTE_0
    SAI_STATUS_INVALID_ATTRIBUTE_MAX = sai_headers.SAI_STATUS_INVALID_ATTRIBUTE_MAX
    SAI_STATUS_INVALID_ATTR_VALUE_0 = sai_headers.SAI_STATUS_INVALID_ATTR_VALUE_0
    SAI_STATUS_INVALID_ATTR_VALUE_MAX = sai_headers.SAI_STATUS_INVALID_ATTR_VALUE_MAX
    SAI_STATUS_ATTR_NOT_IMPLEMENTED_0 = sai_headers.SAI_STATUS_ATTR_NOT_IMPLEMENTED_0
    SAI_STATUS_ATTR_NOT_IMPLEMENTED_MAX = sai_headers.SAI_STATUS_ATTR_NOT_IMPLEMENTED_MAX
    SAI_STATUS_UNKNOWN_ATTRIBUTE_0 = sai_headers.SAI_STATUS_UNKNOWN_ATTRIBUTE_0
    SAI_STATUS_UNKNOWN_ATTRIBUTE_MAX = sai_headers.SAI_STATUS_UNKNOWN_ATTRIBUTE_MAX
    SAI_STATUS_ATTR_NOT_SUPPORTED_0 = sai_headers.SAI_STATUS_ATTR_NOT_SUPPORTED_0
    SAI_STATUS_ATTR_NOT_SUPPORTED_MAX = sai_headers.SAI_STATUS_ATTR_NOT_SUPPORTED_MAX
