# Based on the SONiC VPP startup configuration
# https://github.com/sonic-net/sonic-platform-vpp/blob/2b71bbd7c7197212e34d754df564e6cb11ea9d93/docker-sonic-vpp/conf/startup.conf.tmpl#L4
unix {
    nodaemon
    log /var/log/vpp/vpp.log
    full-coredump
    cli-listen /run/vpp/cli.sock
    poll-sleep-usec 100
    exec /etc/vpp/init.cli
}

api-trace {
    on
    nitems 32768
}

api-segment {
    global-size 256M
    api-size 64M
}

socksvr {
    default
}

memory {
    main-heap-size 2G
}

l3fib {
    fib-entry-pool-size 256K
    load-balance-pool-size 256K
    ip4-mtrie-pool-size 256K
}

ip6 {
    heap-size 128M
}

plugins {
    plugin default { disable }
    plugin af_packet_plugin.so { enable }
    plugin tap_plugin.so { enable }
    plugin linux_cp_plugin.so { enable }
    plugin linux_nl_plugin.so { enable }
    plugin acl_plugin.so { enable }
    plugin vxlan_plugin.so { enable }
    plugin tunterm_acl_plugin.so { enable }
    plugin ip_validate_plugin.so { enable }
    plugin sflow_plugin.so { enable }
}

linux-cp {
    lcp-auto-subint
}

buffers {
    buffers-per-numa 16384
}