name: sc-standalone-deb11-publish

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/sc-standalone-deb11-publish.yml'
      - 'dockerfiles/bullseye/Dockerfile'
      - 'npu/broadcom/BCM56850/saivs/Dockerfile'
      - 'npu/broadcom/BCM56850/saivs/Dockerfile.saithrift'
      - 'common/**'
      - 'cli/**'
      - 'scripts/**'
      - 'configs/**'
      - 'setup.py'
      - 'build.sh'
      - '.dockerignore'
      - 'sai.env'

jobs:
  build-sc-standalone:
    name: Build SAI Challenger standalone image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: git submodule update --init
    - name: Build standalone Docker image
      run: ./build.sh -i standalone -o deb11
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: plvisiondevs
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Create a tag for DockerHub
      run: docker tag sc-trident2-saivs:bullseye plvisiondevs/sc-trident2-saivs:bullseye-latest
    - name: docker push sc-trident2-saivs
      run: docker push plvisiondevs/sc-trident2-saivs:bullseye-latest
    - name: Build standalone Docker image with SAI thrift
      run: ./build.sh -i standalone -s thrift -o deb11
    - name: Create a tag for DockerHub
      run: docker tag sc-thrift-trident2-saivs:bullseye plvisiondevs/sc-thrift-trident2-saivs:bullseye-latest
    - name: docker push sc-thrift-trident2-saivs
      run: docker push plvisiondevs/sc-thrift-trident2-saivs:bullseye-latest
